[build]
builder = "nixpacks"

[deploy]
startCommand = "cd server && node dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.nixpacks]
providers = ["nodejs"]
