services:
  db:
    image: postgres:16
    container_name: gymfonty-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gymfonty
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:


